env:
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
rules:
  "comma-dangle": ["error", "never"]
  "prefer-destructuring": ["error", { "object": false, "array": false }]
overrides:
  - files:
      - "*.test.js"
    rules:
      no-unused-expressions: "off"
