language: node_js
cache:
directories:
- node_modules
notifications:
email: false
branches:
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: Bc1iy8CE+kke+MjFpyhJIJJnEno1L9RVCPzZceLlT3mAu2aJ5oD9aluzusIiku+lA+pHar7xUnJyxY+1a8myFMJFMzPoaiKCFg4JVMhEzLBb7d7bJlxw6Q/6s4UFPWSmWeJqLYu0AV4iHoCLewkjNcz6kP4aZ94oQJjDbn+h+M37Vr0gbtG/YKTKK4FIOJ67CQnXM5vOcq+ZV7PmYvIVkjwYAz318hyZVLcjP2rn0mo6qAScUSCFZMMU/y4bc0n0c5Mk1m9BuZiCqRZkuxzEAtNpUI+68/n0YxU4fmXJmt/+vXVAwT4MVKnOgo7dS0zb0y29SfbkoI5Qg9gEgVOIUo84sH01UvwaWLutpeulh4sV/ll0KBuqbG1bEcdF28iNodxHrovWI7G9Xhy9Cw+cGO5rVm5lcwX2zbZ1VdJBQzFCGSaLYwbcG8glNxeFjVD96TrIdoL/RssVmNg24ilrsClyMMzPbuou/12PpAVRx/O+31vDaFHlT4MmqT+vyGJi6ML2zC72n4uS9ivSjs46Huqk584dwJmklGFHCgbGhExwKz76Gv9MP9xTjZxG4z+1wStOtOSvEchxnUSyhjElQmSC4u7aB0QbxNandi/KWeVOQFg7T8eTKgnucli5DnHRYZW2JwVy1rpvJNpWfu9I5pNDxxRMG1l06GSlQPSEhiA=
  - secure: hKtZVlkhitk6Sl+Pk10tWrVLe9RPPWmFjNc3vtviDJvU7fLpA0ipi3M5U+YzgXnBdX3wfueSQadfQrivVsXTacug485AyvkJaNfGHu5rEEnj6NmNGna93dT2XbmmGlghIBRkgg5mp8H5Lp37uldQdLT90/k7I/Ulp7svmVav4LfZ78w/SRYHU1A9zYYajHo7xhzECb5mab2d0VxuiVG6Dg4gfKxZdVktmc0Cyw5iETLhMqFrtOCpsTp3DUtsL6S1KxEzVgPUPE7bOQEXE+5WK70HZvynRlpkzsFcanzMWgcRdXpDQBTzd0Jqo2efPJuSnjoVXTgABU2n7SQvtPD2Qwr1BVgSeyA9yPvBHMLrIN1SJISTSN4xfZzTdJoFExdBFc+Sn+Trclg8XwWxoZg6kokBvU3TEO24BBPn99Mi4YBjgEVuoFmGyFDj2CRvp5JYh9kLIUwPuOFw/c8DX0BKtMuKI4Rf0nRH06pKTtejcD+3owW3YTVjDgFVSLw0y/5hVtTLwEJf1xwIYhY07VLr71dj2YC/d0sUJKQD2xqQHyMnrkX2kqd6o03pxnlBfDxlC8yrgE5RljcvWeH4l17vPNU/nE/3x5EYI9IN5WettrKQdFFPZF7hUx3G9S1ZrJezWSSgkaYr+D9wLwAK3WIzKMXS1sHngxKAQAGxUvqUgQ4=
