language: node_js
cache:
directories:
- node_modules
notifications:
email: false
branches:
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: Bc1iy8CE+kke+MjFpyhJIJJnEno1L9RVCPzZceLlT3mAu2aJ5oD9aluzusIiku+lA+pHar7xUnJyxY+1a8myFMJFMzPoaiKCFg4JVMhEzLBb7d7bJlxw6Q/6s4UFPWSmWeJqLYu0AV4iHoCLewkjNcz6kP4aZ94oQJjDbn+h+M37Vr0gbtG/YKTKK4FIOJ67CQnXM5vOcq+ZV7PmYvIVkjwYAz318hyZVLcjP2rn0mo6qAScUSCFZMMU/y4bc0n0c5Mk1m9BuZiCqRZkuxzEAtNpUI+68/n0YxU4fmXJmt/+vXVAwT4MVKnOgo7dS0zb0y29SfbkoI5Qg9gEgVOIUo84sH01UvwaWLutpeulh4sV/ll0KBuqbG1bEcdF28iNodxHrovWI7G9Xhy9Cw+cGO5rVm5lcwX2zbZ1VdJBQzFCGSaLYwbcG8glNxeFjVD96TrIdoL/RssVmNg24ilrsClyMMzPbuou/12PpAVRx/O+31vDaFHlT4MmqT+vyGJi6ML2zC72n4uS9ivSjs46Huqk584dwJmklGFHCgbGhExwKz76Gv9MP9xTjZxG4z+1wStOtOSvEchxnUSyhjElQmSC4u7aB0QbxNandi/KWeVOQFg7T8eTKgnucli5DnHRYZW2JwVy1rpvJNpWfu9I5pNDxxRMG1l06GSlQPSEhiA=
